//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:2.0.50727.3074
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Codice sorgente generato automaticamente da xsd, versione=2.0.50727.3038.
// 
namespace prevent.calendar {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Parametri {
        
        private string[] idSitoField;
        
        private System.DateTime dataInizioField;
        
        private System.DateTime dataFineField;
        
        private string tipoGSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IdSito", DataType="positiveInteger")]
        public string[] IdSito {
            get {
                return this.idSitoField;
            }
            set {
                this.idSitoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime DataInizio {
            get {
                return this.dataInizioField;
            }
            set {
                this.dataInizioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime DataFine {
            get {
                return this.dataFineField;
            }
            set {
                this.dataFineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TipoGS {
            get {
                return this.tipoGSField;
            }
            set {
                this.tipoGSField = value;
            }
        }
    }
}
