//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.1
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Codice sorgente generato automaticamente da xsd, versione=4.0.30319.1.
// 
namespace prevent.prenotazione {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Parametri {
        
        private ParametriRigaPercorsoVisita[] rigaPercorsoVisitaField;
        
        private ParametriRigaBiglietti[] rigaBigliettiField;
        
        private string denominazioneField;
        
        private string paxTotaliField;
        
        private string codiceTransWinTicketField;
        
        private string tipoGSField;
        
        private string scuolaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RigaPercorsoVisita")]
        public ParametriRigaPercorsoVisita[] RigaPercorsoVisita {
            get {
                return this.rigaPercorsoVisitaField;
            }
            set {
                this.rigaPercorsoVisitaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RigaBiglietti")]
        public ParametriRigaBiglietti[] RigaBiglietti {
            get {
                return this.rigaBigliettiField;
            }
            set {
                this.rigaBigliettiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Denominazione {
            get {
                return this.denominazioneField;
            }
            set {
                this.denominazioneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string PaxTotali {
            get {
                return this.paxTotaliField;
            }
            set {
                this.paxTotaliField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodiceTransWinTicket {
            get {
                return this.codiceTransWinTicketField;
            }
            set {
                this.codiceTransWinTicketField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TipoGS {
            get {
                return this.tipoGSField;
            }
            set {
                this.tipoGSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Scuola {
            get {
                return this.scuolaField;
            }
            set {
                this.scuolaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ParametriRigaPercorsoVisita {
        
        private string idMostraField;
        
        private System.DateTime dataVisitaField;
        
        private string oraVisitaField;
        
        private string paxVisitaField;
        
        /// <remarks/>
        public string IdMostra {
            get {
                return this.idMostraField;
            }
            set {
                this.idMostraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DataVisita {
            get {
                return this.dataVisitaField;
            }
            set {
                this.dataVisitaField = value;
            }
        }
        
        /// <remarks/>
        public string OraVisita {
            get {
                return this.oraVisitaField;
            }
            set {
                this.oraVisitaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
        public string PaxVisita {
            get {
                return this.paxVisitaField;
            }
            set {
                this.paxVisitaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ParametriRigaBiglietti {
        
        private string idTipoBigliettoField;
        
        private string quantitaField;
        
        /// <remarks/>
        public string IdTipoBiglietto {
            get {
                return this.idTipoBigliettoField;
            }
            set {
                this.idTipoBigliettoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
        public string Quantita {
            get {
                return this.quantitaField;
            }
            set {
                this.quantitaField = value;
            }
        }
    }
}
